auto_place_exclude = [
    "Shell_TrayWnd",
    "NotifyIconOverflowWindow",
    "tooltips_class32",
]

[grid]
columns = 4
rows = 3

[monitor_grids]

[[app_rules]]
exe_name = "Code"
col = 13
row = 6
col_span = 7
row_span = 6

[[app_rules]]
exe_name = "Google Chrome"
col = 0
row = 0
col_span = 7
row_span = 6

[[app_rules]]
monitor = "2"
exe_name = "Google Chrome"
col = 0
row = 6
col_span = 8
row_span = 6

[[app_rules]]
monitor = "2"
exe_name = "Notion"
col = 0
row = 6
col_span = 7
row_span = 6

[[app_rules]]
monitor = '\\.\DISPLAY2'
exe_name = "gridsnap.exe"
col = 0
row = 0
col_span = 1
row_span = 1

[[app_rules]]
monitor = '\\.\DISPLAY2'
exe_name = "explorer.exe"
col = 17
row = 11
col_span = 3
row_span = 1

[[app_rules]]
monitor = '\\.\DISPLAY2'
exe_name = "chrome.exe"
col = 0
row = 0
col_span = 8
row_span = 8

[[app_rules]]
monitor = '\\.\DISPLAY1'
exe_name = "chrome.exe"
col = 1
row = 3
col_span = 18
row_span = 9

[[app_rules]]
monitor = "1"
exe_name = "Google Chrome"
col = 0
row = 0
col_span = 16
row_span = 9

[overlay]
enabled = true
color_argb = 1073774847

[titlebar]
hide_for_classes = []
